### ISSUE TITLE
[1.17.x] Stone blocks from Twigs 1.0.2 do not drop items when harvested with Advanced Netherite pickaxes

### ISSUE THREAD

**Issue by Minionade** [Autovw/AdvancedNetheriteFabric#1]
Stone-based blocks from the Twigs mod i.e. twigs:schist and twigs:cobblestone_bricks are able to be harvested with vanilla and other modded pickaxes, but, while Advanced Netherite pickaxes do break the blocks fairly quickly, they do not yield any items after breaking the block. (tested with minecraft:diamond_pickaxe, dragonloot:dragon_pickaxe, and all tiers of advanced netherite pickaxes.)

Tested with Advanced Netherite version 1.1.0 for Fabric 1.17.x, Twigs 1.0.2, and Dragon Loot 1.0.9

**Comment by Autovw** [comment]
Thanks for reporting. I'm still fairly new to Fabric and I didn't know there were additional steps to support modded blocks.
The issue should be fixed in the next update!

**Comment by Minionade** [comment]
Thanks for the peace of mind!  This mod is essential to my vanilla plus experience, so I'm glad to help in any ways I can!

**Comment by Autovw** [comment]
Thanks for taking your time, I've released the update with the fix.
Please let me know if more issues arise.
