### ISSUE TITLE
Pacify piglins don't work

### ISSUE THREAD

**Issue by MOOOOs** [Autovw/AdvancedNetheriteFabric#11]
For some reason Pacify piglins on full Netherite-Diamond set won't work same for Netherite-Gold armor set

**Comment by MOOOOs** [comment]
thats bug label not question label btw

**Comment by Autovw** [comment]
Just tested this on my end and it works completely fine. Gonna need some more information on this.

What version are you using?

Any errors in the log?

Are you using a modpack?

etc.

**Comment by MOOOOs** [comment]
1.19.2 no errors no modpack

**Comment by Autovw** [comment]
I'm sorry but I can't debug the issue with the information provided. Like I said it works fine for me on version ``1.6.4-1.19.2``. 

Did you attack the piglins? 

Did you open a chest?

Can you try with vanilla gold armor too?

**Comment by MOOOOs** [comment]
piglins stop attacking once i apply vanilla gold armor piece also i didn't attack or opened chest

**Comment by Autovw** [comment]
Well I'm gonna need the logs then.

If you could share the ``debug.log`` that would be appreciated, other than that I have absolutely no idea what the issue could be here.

**Comment by MOOOOs** [comment]
[debug.log](https://github.com/Autovw/AdvancedNetheriteFabric/files/9638758/debug.log)

**Comment by MOOOOs** [comment]
Also im on Fabric mod loader

**Comment by Autovw** [comment]
That's a Forge log from August 30th.

**Comment by MOOOOs** [comment]
interesting why it didn't create it now when im playing

**Comment by MOOOOs** [comment]
its last debug log i got

**Comment by Autovw** [comment]
Try closing your game

**Comment by MOOOOs** [comment]
i just did same debug log

**Comment by MOOOOs** [comment]
maybe fabric doesn't create debug logs

**Comment by Autovw** [comment]
It definitely should, but it could be that you are using the CurseForge app, in which case there isn't a debug log unless you turn it on. You can also provide the ``latest.log`` if that one happens to be up to date.

**Comment by MOOOOs** [comment]
im not using curseforge app i play from minecraft.net launcher

**Comment by MOOOOs** [comment]
[latest.log](https://github.com/Autovw/AdvancedNetheriteFabric/files/9638779/latest.log)

**Comment by Autovw** [comment]
I'm sorry but I'm unable to find anything in the log and can't even reproduce the issue on my end. For these reasons I'm gonna need to close this issue, but it can be re-opened if someone can come with actual evidence of this feature being broken.

The only thing I can think of right now is that there might be a mod on your mod list which is secretly disabling the pacify piglins perk.

**Comment by MOOOOs** [comment]
have you tried to reproduce it on Fabric?

**Comment by Autovw** [comment]
Yes. You reported to the Fabric repository of my mod so that was the first version I tested. I've checked all the code related to the perk and tested in-game to verify.

**Comment by MOOOOs** [comment]
looks like its some mod i disabled all and kept only advanced netherite and fabric api make pacify piglins work testing now what mod do that and if when find out will tell what mod does that maybe there can be some fix

**Comment by MOOOOs** [comment]
It looks like for some reason Vanity slots https://www.curseforge.com/minecraft/mc-mods/vanityslots mod disables pacified piglins have tested with Advanced Netherite, Fabric API, Trinket and VanitySlots you prob can reproduce this easily

**Comment by Autovw** [comment]
If Vanity Slots is causing this I recommend reporting the issue to them as there's not much I can do about it.

**Comment by MOOOOs** [comment]
yeah i did report on that mod github will see what say

**Comment by NyakoFox** [comment]
just fixed this on our end, sorry about that
