### ISSUE TITLE
Crash when Rendering Entity In World

### ISSUE THREAD

**Issue by GourmetTinCan** [Autovw/AdvancedNetheriteFabric#12]
Hey there! I appear to be crashing from the armor rendering in the world, not really sure why. I have the crash report saved here: https://pastebin.com/ydrzn9pt .

I've tested the mod on the same quilt version [0.17.10, minecraft vers. 1.19.2] running by itself along side the same version of QFAPI and QSL in the crash report, and it works fine. Also tested it on Fabric 0.14.13 [minecraft vers. 1.19.2] with the latest Fabric API and it also works fine.

No crashes while holding it as an item in the inventory, in hand, or crafting, just when I equip it. Attempting to reload into the world makes it crash as soon as it's loaded.

One thing I did find is that by disabling my shader pack I'm able to equip the armor and walk around, but going into third person crashes the game. Here's a crash report from that: https://pastebin.com/vEaxbSLn

Guessing it has something to do with Iris?

**Comment by GourmetTinCan** [comment]
> 

Just tested this with a friend and I can a little more detail if it helps.
Upon loading into my server without my shaderpacks enabled I didn't crash at all since I haven't gone into third person, so I tested to see if someone else looking at me would cause them to crash. Seems like whenever another player walks into distance to render my character they crash. They were walking in my direction and once the chunk I was in loaded for them they crashed, without actually making direct line of sight with my character.

**Comment by Autovw** [comment]
Hey, thanks for your report!

To explain what is happening:
In versions of the mod prior to MC 1.19.3 there's the need for a "Mixin" injection to load armor textures from the correct namespace. By default, Minecraft only supports loading armor textures from the ``minecraft`` namespace. To prevent incompatability and allowing texture packs for my mod to work for the versions of both modloaders (Forge and Fabric) I need to load these textures from the ``advancednetherite`` namespace instead.

However, it seems that another mod is also using a Mixin that is preventing my safe Mixin injection from happening, causing Minecraft to look for an invalid texture. Based on your findings I'm assuming this is Iris. I did some testing with my mod in the development environment, but I'm unable to replicate the same crash.

I removed the Mixin in 1.19.3 versions as Fabric API ``0.62.0`` (and above) already covers this for mods. What I can do is remove the Mixin for MC 1.19.2 as well and ask users to install Fabric API ``0.62.0`` (or anything newer) to see if that would fix the issue. I'm however not familiar with Quilt, and do not officially support it. But I assume Quilt's API also supports this.

**Comment by Autovw** [comment]
I've published a new version labeled as ``1.6.6-1.19.2``. This version removes the armor texture loading Mixin I referred to in my previous comment. Please let me know if the issue has been resolved or not. If the issue keeps occurring it might be worth opening an issue on the Iris issue tracker with a reference to this issue.
