### ISSUE TITLE
Add Support for wildfire's gender mod

### ISSUE THREAD

**Issue by MommyLexie** [Autovw/AdvancedNetheriteFabric#13]
![image](https://user-images.githubusercontent.com/81419755/215115899-8731099c-3336-4cec-9745-aca6a4957448.png)

**Comment by Autovw** [comment]
Hey,

Thanks for your feature request.
I understand that there's a good use-case for this, but I'll have to leave this open for now.
The mod in question offers limited documentation for developers, and I'm unsure what to think about the design of the API being provided. I hope there's a temporary workaround provided by the mod, I'll have to look into this at a later date.
