### ISSUE TITLE
client Launch crash on 1.18.2

### ISSUE THREAD

**Issue by netcore10** [Autovw/AdvancedNetheriteFabric#15]
https://paste.atlauncher.com/view/a62e90c8-6f10-4e9f-926c-f74ebc2796f0

**Comment by Autovw** [comment]
Advanced Netherite is not mentioned anywhere during the crash, instead you'll have to find the mod responsible for this line: ``Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:optifine/cit/elytras/angel wings/angel_wings.properties``

**Comment by netcore10** [comment]
Thanks for the input! Sorry for wasting your time on this.
