### ISSUE TITLE
Incompatibility with experimental smithing table feature

### ISSUE THREAD

**Issue by loogchin** [Autovw/AdvancedNetheriteFabric#17]
![image](https://user-images.githubusercontent.com/87599145/236510495-560474ff-25b6-4ee9-8eaf-4ebc313e433f.png)
![image](https://user-images.githubusercontent.com/87599145/236510485-f3a9c35b-1ced-4cbb-bce2-a3d4f4204d69.png)

**Comment by Autovw** [comment]
This mod doesn't officially support Mojang's experimental snapshot features _yet_. There will likely be support in the near future.

**Comment by Autovw** [comment]
Support for the new smithing table has been added in the 1.20 update of Advanced Netherite.
