### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by dangamerx7** [Autovw/AdvancedNetheriteFabric#19]
My client is crashing after I either put my netherite-diamond armor on an armor stand or equip it.  

https://bytebin.lucko.me/cGJRZRyw1U

**Comment by Autovw** [comment]
Issue caused by other mods using poorly written mixins to change a feature that is already covered by Fabric API. There's nothing on my end that I can do about this.

The log is pointing to ``chime``, perhaps you're better off reporting the issue to them.
