### ISSUE TITLE
forge reference item in fabric version

### ISSUE THREAD

**Issue by wackoamd1** [Autovw/AdvancedNetheriteFabric#3]
there is a error popping up in my log
Parsing error loading custom advancement advancednetherite:recipes/netherite_ingots: Unknown item tag 'forge:ingots/netherite'
ofc its a unknown item this is fabric

**Comment by Autovw** [comment]
Which version of the mod are you using?
Thought I fixed that issue a while ago.

**Comment by wackoamd1** [comment]
advancednetherite-fabric-1.3.0-1.18.1.jar

**Comment by Autovw** [comment]
Strange, I'll look into it.

**Comment by Autovw** [comment]
Thanks for the report, even though it wasn't anything serious I've fixed it in v1.3.1.
