### ISSUE TITLE
Knockback resistance is not applied

### ISSUE THREAD

**Issue by lunarpatriots** [Autovw/AdvancedNetheriteFabric#4]
Netherite armor's knockback resistance is not present on all upgrade tiers.

**Comment by Autovw** [comment]
I've investigated it and it seems to be an issue with knockback resistance not being applied due to one little thingy being hardcoded in vanilla. Forge patches this but on Fabric it's a different story which means writing another hacky Mixin. Nice.

I'll get a fix out for this asap.

**Comment by Autovw** [comment]
Thanks for the report, issue is fixed in v1.4.0
