### ISSUE TITLE
[1.18.2] LevelZ compatibility

### ISSUE THREAD

**Issue by PIPILAN** [Autovw/AdvancedNetheriteFabric#7]
I ran into the same [problem](https://github.com/Globox1997/LevelZ/issues/99#issuecomment-1144131769) as the one below:
> At least for Vanilla Hammers, the problem with using the material definition instead is that hammers don't count as a "Minecraft:tool" and so no restrictions are applied. Same with **Advanced Netherite**, a netherite_diamond_helmet doesn't count as "Minecraft:armor".
----
levelz wiki: https://github.com/Globox1997/LevelZ
An example of one of those categories is here:
> {
    "replace": false,
    "skill": "defense",
    "level": 8,
    "item": "minecraft:armor",
    "material": "iron"
}
It takes a fifth argument called "material" to determine which material of items will be locked.
Each of these items has to be in the corresponding fabric item tag.
----
I tested it myself and I can add a level limit to swords/tools/axes but not armor.

**Ignore Smithing**, which is restricted by another method

 swords √
> {
    "replace": false,
    "skill": "strength",
    "level": 24,
    "item": "minecraft:sword",
    "material": "netherite_iron"
}

![image](https://user-images.githubusercontent.com/38380796/173982658-a149165c-2dd5-4b9d-a319-fddb8e3da6d3.png)

armor ×
> {
    "replace": false,
    "skill": "denfense",
    "level": 24,
    "item": "minecraft:armor",
    "material": "netherite_iron"
}

![image](https://user-images.githubusercontent.com/38380796/173982715-01e71d5b-d52d-4103-8d91-33ffa597e7e3.png)

I don't know why, but I guess there's something wrong with the armor material?

**Comment by Autovw** [comment]
I'm guessing you just made an accidental typo here which is causing the issue:
> "skill": "denfense",

Also, as a note: I'm not doing anything weird with the armor in my mod that I'm aware of. Seems more like an issue on LevelZ end, but I'm currently not in a position to verify that.

**Comment by PIPILAN** [comment]
I'm sorry about the accidental typo, but it still didn't work when I corrected it. I don't know what the problem was.

**Comment by Jurklein** [comment]
I think the correct way of doing it is this:
(put it in your data/levelz/items folder)
```
{
"replace": true,
"skill": "defense",
"level": 24,
"item": "minecraft:custom_item",
"object": "advancednetherite:netherite_iron_chestplate"
}
````

Don't forget to set "replace" to true!
