### ISSUE TITLE
Will Their Be Support for the Enderite mod?

### ISSUE THREAD

**Issue by SnowedInOwl** [Autovw/AdvancedNetheriteFabric#9]
The mod in question ( https://www.curseforge.com/minecraft/mc-mods/enderite-mod-for-fabric )

I only ask as it would be nice to it work well with that mod

**Comment by Autovw** [comment]
Can you explain what doesn't work well?

If you're talking about adding Enderite variants to this mod, the answer will be no. That would be a better fit for a possible "compatibility" mod between Advanced Netherite and Enderite Mod simply because the goal of this mod is to expand on Netherite

**Comment by SnowedInOwl** [comment]
Ok Understandable. Have a great Day.
